###
GET http://localhost:3333/users
Content-Type: application/json

###
post http://localhost:3333/users
Content-Type: application/json

{
  "firstName":"Elisa",
  "lastName":"Rafael",
  "email":"Elisa@Lisa11.com",
  "password":"10101010"
}

###
patch http://localhost:3333/users/fd58c004-7393-4252-bc75-396d7edd3108
Content-Type: application/json

{
  
  "email":"penaswild1@gmail.com"

}

###
DELETE http://localhost:3333/users/fd58c004-7393-4252-bc75-396d7edd3108
Content-Type: application/json